// This file is @generated by prost-build.
/// 通用响应
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Response {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
/// 带 update_id 的响应（用于订单取消等需要返回更新后 update_id 的场景）
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResponseWithUpdateId {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub update_id: i64,
}
/// 充值通知
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DepositRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub amount: ::prost::alloc::string::String,
    /// usdc就是usdc token就是token_id
    #[prost(string, tag = "3")]
    pub token_id: ::prost::alloc::string::String,
    /// 资产变化追溯标识符 这里就是交易hash
    #[prost(string, tag = "4")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub event_id: i64,
    #[prost(int32, tag = "6")]
    pub market_id: i32,
    /// 用于websocket推送
    #[prost(string, tag = "7")]
    pub privy_id: ::prost::alloc::string::String,
    /// 用于websocket推送
    #[prost(string, tag = "8")]
    pub outcome_name: ::prost::alloc::string::String,
}
/// 提现通知
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WithdrawRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub amount: ::prost::alloc::string::String,
    /// usdc就是usdc token就是token_id
    #[prost(string, tag = "3")]
    pub token_id: ::prost::alloc::string::String,
    /// 资产变化追溯标识符 这里就是交易hash
    #[prost(string, tag = "4")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub event_id: i64,
    #[prost(int32, tag = "6")]
    pub market_id: i32,
    /// 用于websocket推送
    #[prost(string, tag = "7")]
    pub privy_id: ::prost::alloc::string::String,
    /// 用于websocket推送
    #[prost(string, tag = "8")]
    pub outcome_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateOrderRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(int64, tag = "2")]
    pub event_id: i64,
    #[prost(int32, tag = "3")]
    pub market_id: i32,
    #[prost(string, tag = "4")]
    pub outcome: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub token_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub order_side: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub order_type: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub price: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub quantity: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub volume: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "11")]
    pub signature_order_msg: ::core::option::Option<SignatureOrderMsg>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignatureOrderMsg {
    #[prost(string, tag = "1")]
    pub expiration: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub fee_rate_bps: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub maker: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub maker_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub nonce: ::prost::alloc::string::String,
    #[prost(int64, tag = "6")]
    pub salt: i64,
    #[prost(string, tag = "7")]
    pub side: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int32, tag = "9")]
    pub signature_type: i32,
    #[prost(string, tag = "10")]
    pub signer: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub taker: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub taker_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub token_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateOrderResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub order_id: ::prost::alloc::string::String,
    /// 订单的 update_id，新订单为 1
    #[prost(int64, tag = "4")]
    pub update_id: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrderRejectedRequest {
    /// 用户id
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
}
/// 限价单才能cancel
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelOrderRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub cancelled_quantity: ::prost::alloc::string::String,
    /// 限价单就是价格\*取消数量 市价单包括退还的钱
    #[prost(string, tag = "4")]
    pub volume: ::prost::alloc::string::String,
}
/// 插入trade更新order 然后返回批次的signature信息
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradeRequest {
    #[prost(message, optional, tag = "1")]
    pub taker_trade_info: ::core::option::Option<TakerTradeInfo>,
    #[prost(message, repeated, tag = "2")]
    pub maker_trade_infos: ::prost::alloc::vec::Vec<MakerTradeInfo>,
    #[prost(string, tag = "3")]
    pub trade_id: ::prost::alloc::string::String,
    /// 撮合成交时间戳
    #[prost(int64, tag = "4")]
    pub timestamp: i64,
    #[prost(int64, tag = "5")]
    pub event_id: i64,
    #[prost(int32, tag = "6")]
    pub market_id: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TakerTradeInfo {
    #[prost(int64, tag = "5")]
    pub taker_id: i64,
    #[prost(string, tag = "6")]
    pub taker_order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub taker_order_side: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub taker_token_id: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub taker_usdc_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub taker_token_amount: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MakerTradeInfo {
    #[prost(int64, tag = "1")]
    pub maker_id: i64,
    #[prost(string, tag = "2")]
    pub maker_order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub maker_order_side: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub maker_token_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub maker_usdc_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub maker_token_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub maker_price: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrderUpdateId {
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub update_id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradeResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub signature_order_msgs: ::prost::alloc::vec::Vec<SignatureOrderMsg>,
    /// 所有涉及订单的 update_id（taker + makers）
    #[prost(message, repeated, tag = "4")]
    pub order_update_ids: ::prost::alloc::vec::Vec<OrderUpdateId>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradeOnchainSendResultRequest {
    #[prost(string, tag = "1")]
    pub trade_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub event_id: i64,
    #[prost(int32, tag = "3")]
    pub market_id: i32,
    #[prost(message, optional, tag = "4")]
    pub taker_trade_info: ::core::option::Option<TakerTradeOnchainInfo>,
    #[prost(message, repeated, tag = "5")]
    pub maker_trade_infos: ::prost::alloc::vec::Vec<MakerTradeOnchainInfo>,
    #[prost(string, tag = "6")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub success: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TakerTradeOnchainInfo {
    #[prost(string, tag = "1")]
    pub taker_side: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub taker_user_id: i64,
    #[prost(string, tag = "4")]
    pub taker_usdc_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub taker_token_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub taker_token_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub taker_order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub real_taker_usdc_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub real_taker_token_amount: ::prost::alloc::string::String,
    /// 限价单是没有refund的 市价单有因为市价单是先冻结资产 没成交的就取消了所以有refund 所以解冻这里要带上可能refund的金额
    #[prost(string, tag = "10")]
    pub taker_unfreeze_amount: ::prost::alloc::string::String,
    /// 用于websocket推送
    #[prost(string, tag = "11")]
    pub taker_privy_user_id: ::prost::alloc::string::String,
    /// 用于websocket推送
    #[prost(string, tag = "12")]
    pub taker_outcome_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MakerTradeOnchainInfo {
    #[prost(string, tag = "1")]
    pub maker_side: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub maker_user_id: i64,
    #[prost(string, tag = "4")]
    pub maker_usdc_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub maker_token_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub maker_token_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub maker_order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub maker_price: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub real_maker_usdc_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub real_maker_token_amount: ::prost::alloc::string::String,
    /// 用于websocket推送
    #[prost(string, tag = "11")]
    pub maker_privy_user_id: ::prost::alloc::string::String,
    /// 用于websocket推送
    #[prost(string, tag = "12")]
    pub maker_outcome_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SplitRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub usdc_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub token_0_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub token_1_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub token_0_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub token_1_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(int64, tag = "8")]
    pub event_id: i64,
    #[prost(int32, tag = "9")]
    pub market_id: i32,
    /// 用于websocket推送
    #[prost(string, tag = "10")]
    pub privy_id: ::prost::alloc::string::String,
    /// token_0 outcome名称
    #[prost(string, tag = "11")]
    pub outcome_name_0: ::prost::alloc::string::String,
    /// token_1 outcome名称
    #[prost(string, tag = "12")]
    pub outcome_name_1: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MergeRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub token_0_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub token_1_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub token_0_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub token_1_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub usdc_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(int64, tag = "8")]
    pub event_id: i64,
    #[prost(int32, tag = "9")]
    pub market_id: i32,
    /// 用于websocket推送
    #[prost(string, tag = "10")]
    pub privy_id: ::prost::alloc::string::String,
    /// token_0 outcome名称
    #[prost(string, tag = "11")]
    pub outcome_name_0: ::prost::alloc::string::String,
    /// token_1 outcome名称
    #[prost(string, tag = "12")]
    pub outcome_name_1: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RedeemRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub token_id_0: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub token_id_1: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub usdc_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(int64, tag = "8")]
    pub event_id: i64,
    #[prost(int32, tag = "9")]
    pub market_id: i32,
    /// 用于websocket推送
    #[prost(string, tag = "10")]
    pub privy_id: ::prost::alloc::string::String,
    /// token_0 outcome名称
    #[prost(string, tag = "11")]
    pub outcome_name_0: ::prost::alloc::string::String,
    /// token_1 outcome名称
    #[prost(string, tag = "12")]
    pub outcome_name_1: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod asset_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Asset服务定义
    #[derive(Debug, Clone)]
    pub struct AssetServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AssetServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AssetServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AssetServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AssetServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn deposit(
            &mut self,
            request: impl tonic::IntoRequest<super::DepositRequest>,
        ) -> std::result::Result<tonic::Response<super::Response>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/asset.AssetService/Deposit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("asset.AssetService", "Deposit"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn withdraw(
            &mut self,
            request: impl tonic::IntoRequest<super::WithdrawRequest>,
        ) -> std::result::Result<tonic::Response<super::Response>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/asset.AssetService/Withdraw",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("asset.AssetService", "Withdraw"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn create_order(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateOrderResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/asset.AssetService/CreateOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("asset.AssetService", "CreateOrder"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn order_rejected(
            &mut self,
            request: impl tonic::IntoRequest<super::OrderRejectedRequest>,
        ) -> std::result::Result<tonic::Response<super::Response>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/asset.AssetService/OrderRejected",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("asset.AssetService", "OrderRejected"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn cancel_order(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ResponseWithUpdateId>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/asset.AssetService/CancelOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("asset.AssetService", "CancelOrder"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn trade(
            &mut self,
            request: impl tonic::IntoRequest<super::TradeRequest>,
        ) -> std::result::Result<tonic::Response<super::TradeResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/asset.AssetService/Trade");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("asset.AssetService", "Trade"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn trade_onchain_send_result(
            &mut self,
            request: impl tonic::IntoRequest<super::TradeOnchainSendResultRequest>,
        ) -> std::result::Result<tonic::Response<super::Response>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/asset.AssetService/TradeOnchainSendResult",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("asset.AssetService", "TradeOnchainSendResult"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn split(
            &mut self,
            request: impl tonic::IntoRequest<super::SplitRequest>,
        ) -> std::result::Result<tonic::Response<super::Response>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/asset.AssetService/Split");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("asset.AssetService", "Split"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn merge(
            &mut self,
            request: impl tonic::IntoRequest<super::MergeRequest>,
        ) -> std::result::Result<tonic::Response<super::Response>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/asset.AssetService/Merge");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("asset.AssetService", "Merge"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn redeem(
            &mut self,
            request: impl tonic::IntoRequest<super::RedeemRequest>,
        ) -> std::result::Result<tonic::Response<super::Response>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/asset.AssetService/Redeem",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("asset.AssetService", "Redeem"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod asset_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AssetServiceServer.
    #[async_trait]
    pub trait AssetService: std::marker::Send + std::marker::Sync + 'static {
        async fn deposit(
            &self,
            request: tonic::Request<super::DepositRequest>,
        ) -> std::result::Result<tonic::Response<super::Response>, tonic::Status>;
        async fn withdraw(
            &self,
            request: tonic::Request<super::WithdrawRequest>,
        ) -> std::result::Result<tonic::Response<super::Response>, tonic::Status>;
        async fn create_order(
            &self,
            request: tonic::Request<super::CreateOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateOrderResponse>,
            tonic::Status,
        >;
        async fn order_rejected(
            &self,
            request: tonic::Request<super::OrderRejectedRequest>,
        ) -> std::result::Result<tonic::Response<super::Response>, tonic::Status>;
        async fn cancel_order(
            &self,
            request: tonic::Request<super::CancelOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ResponseWithUpdateId>,
            tonic::Status,
        >;
        async fn trade(
            &self,
            request: tonic::Request<super::TradeRequest>,
        ) -> std::result::Result<tonic::Response<super::TradeResponse>, tonic::Status>;
        async fn trade_onchain_send_result(
            &self,
            request: tonic::Request<super::TradeOnchainSendResultRequest>,
        ) -> std::result::Result<tonic::Response<super::Response>, tonic::Status>;
        async fn split(
            &self,
            request: tonic::Request<super::SplitRequest>,
        ) -> std::result::Result<tonic::Response<super::Response>, tonic::Status>;
        async fn merge(
            &self,
            request: tonic::Request<super::MergeRequest>,
        ) -> std::result::Result<tonic::Response<super::Response>, tonic::Status>;
        async fn redeem(
            &self,
            request: tonic::Request<super::RedeemRequest>,
        ) -> std::result::Result<tonic::Response<super::Response>, tonic::Status>;
    }
    /// Asset服务定义
    #[derive(Debug)]
    pub struct AssetServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AssetServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AssetServiceServer<T>
    where
        T: AssetService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/asset.AssetService/Deposit" => {
                    #[allow(non_camel_case_types)]
                    struct DepositSvc<T: AssetService>(pub Arc<T>);
                    impl<
                        T: AssetService,
                    > tonic::server::UnaryService<super::DepositRequest>
                    for DepositSvc<T> {
                        type Response = super::Response;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DepositRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AssetService>::deposit(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DepositSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/asset.AssetService/Withdraw" => {
                    #[allow(non_camel_case_types)]
                    struct WithdrawSvc<T: AssetService>(pub Arc<T>);
                    impl<
                        T: AssetService,
                    > tonic::server::UnaryService<super::WithdrawRequest>
                    for WithdrawSvc<T> {
                        type Response = super::Response;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WithdrawRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AssetService>::withdraw(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WithdrawSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/asset.AssetService/CreateOrder" => {
                    #[allow(non_camel_case_types)]
                    struct CreateOrderSvc<T: AssetService>(pub Arc<T>);
                    impl<
                        T: AssetService,
                    > tonic::server::UnaryService<super::CreateOrderRequest>
                    for CreateOrderSvc<T> {
                        type Response = super::CreateOrderResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateOrderRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AssetService>::create_order(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateOrderSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/asset.AssetService/OrderRejected" => {
                    #[allow(non_camel_case_types)]
                    struct OrderRejectedSvc<T: AssetService>(pub Arc<T>);
                    impl<
                        T: AssetService,
                    > tonic::server::UnaryService<super::OrderRejectedRequest>
                    for OrderRejectedSvc<T> {
                        type Response = super::Response;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::OrderRejectedRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AssetService>::order_rejected(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = OrderRejectedSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/asset.AssetService/CancelOrder" => {
                    #[allow(non_camel_case_types)]
                    struct CancelOrderSvc<T: AssetService>(pub Arc<T>);
                    impl<
                        T: AssetService,
                    > tonic::server::UnaryService<super::CancelOrderRequest>
                    for CancelOrderSvc<T> {
                        type Response = super::ResponseWithUpdateId;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CancelOrderRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AssetService>::cancel_order(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CancelOrderSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/asset.AssetService/Trade" => {
                    #[allow(non_camel_case_types)]
                    struct TradeSvc<T: AssetService>(pub Arc<T>);
                    impl<
                        T: AssetService,
                    > tonic::server::UnaryService<super::TradeRequest> for TradeSvc<T> {
                        type Response = super::TradeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TradeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AssetService>::trade(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = TradeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/asset.AssetService/TradeOnchainSendResult" => {
                    #[allow(non_camel_case_types)]
                    struct TradeOnchainSendResultSvc<T: AssetService>(pub Arc<T>);
                    impl<
                        T: AssetService,
                    > tonic::server::UnaryService<super::TradeOnchainSendResultRequest>
                    for TradeOnchainSendResultSvc<T> {
                        type Response = super::Response;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TradeOnchainSendResultRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AssetService>::trade_onchain_send_result(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = TradeOnchainSendResultSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/asset.AssetService/Split" => {
                    #[allow(non_camel_case_types)]
                    struct SplitSvc<T: AssetService>(pub Arc<T>);
                    impl<
                        T: AssetService,
                    > tonic::server::UnaryService<super::SplitRequest> for SplitSvc<T> {
                        type Response = super::Response;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SplitRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AssetService>::split(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SplitSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/asset.AssetService/Merge" => {
                    #[allow(non_camel_case_types)]
                    struct MergeSvc<T: AssetService>(pub Arc<T>);
                    impl<
                        T: AssetService,
                    > tonic::server::UnaryService<super::MergeRequest> for MergeSvc<T> {
                        type Response = super::Response;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MergeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AssetService>::merge(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MergeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/asset.AssetService/Redeem" => {
                    #[allow(non_camel_case_types)]
                    struct RedeemSvc<T: AssetService>(pub Arc<T>);
                    impl<
                        T: AssetService,
                    > tonic::server::UnaryService<super::RedeemRequest>
                    for RedeemSvc<T> {
                        type Response = super::Response;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RedeemRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AssetService>::redeem(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RedeemSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for AssetServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "asset.AssetService";
    impl<T> tonic::server::NamedService for AssetServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
